services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: kali
      MYSQL_DATABASE: table
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - bistro

  flask_app:
    build: .
    container_name: bistro
    image: bakhtawar375/bistro:latest
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: kali
      MYSQL_DATABASE: table
    ports:
      - "5000:5000"
    networks:
      - bistro
    depends_on:
      - database

volumes:
  mysqldata:

networks:
  bistro:
